version: "3.9"

services:
  mongo:
    image: mongo:4.4
    container_name: yadah-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", 'mongosh --eval ''db.adminCommand("ping")'' || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mongo_data:
