services:
  mongo:
    image: mongo:4.4
    container_name: yadah-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080/api
    container_name: yadah-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
