services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080/api
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: yadah-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
